name: Creation

on:
  workflow_dispatch:
    inputs:
      accounts_ondemand:
        description: "Enter the accounts, separated by commas"
      faster:
        description: "Enter a value if you want to use fast version"

  schedule:
    - cron: "0 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub
          pip install pytz
          pip install argparse
      - name: Run script
        if: ${{ github.event.inputs.accounts_ondemand && github.event.inputs.faster }}
        env:
          GH_ACCOUNTS_B64: ${{ secrets.GH_ACCOUNTS_B64 }}
          GOOGLE_SHEETS_TAB_NAME: ${{ secrets.GOOGLE_SHEETS_TAB_NAME }}
          GOOGLE_SHEETS_TOKEN_B64: ${{ secrets.GOOGLE_SHEETS_TOKEN_B64 }}
          GOOGLE_SHEETS_SHEET_ID: ${{ secrets.GOOGLE_SHEETS_SHEET_ID }}
          GOOGLE_SHEETS_CREDENTIALS_B64: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_B64 }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
          CONTAINER_USER: ${{ secrets.CONTAINER_USER }}
          CONTAINER_PASS: ${{ secrets.CONTAINER_PASS }}
          MATRIX: ${{ secrets.MATRIX }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          python genesi.py --accounts_ondemand ${{ github.event.inputs.accounts_ondemand }} --faster ${{ github.event.inputs.faster }}
      - name: Run script with only accounts_ondemand
        if: ${{ github.event.inputs.accounts_ondemand && !github.event.inputs.faster }}
        env:
          GH_ACCOUNTS_B64: ${{ secrets.GH_ACCOUNTS_B64 }}
          GOOGLE_SHEETS_TAB_NAME: ${{ secrets.GOOGLE_SHEETS_TAB_NAME }}
          GOOGLE_SHEETS_TOKEN_B64: ${{ secrets.GOOGLE_SHEETS_TOKEN_B64 }}
          GOOGLE_SHEETS_SHEET_ID: ${{ secrets.GOOGLE_SHEETS_SHEET_ID }}
          GOOGLE_SHEETS_CREDENTIALS_B64: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_B64 }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
          CONTAINER_USER: ${{ secrets.CONTAINER_USER }}
          CONTAINER_PASS: ${{ secrets.CONTAINER_PASS }}
          MATRIX: ${{ secrets.MATRIX }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          python genesi.py --accounts_ondemand ${{ github.event.inputs.accounts_ondemand }}
      - name: Run script with only faster
        if: ${{ !github.event.inputs.accounts_ondemand && github.event.inputs.faster }}
        env:
          GH_ACCOUNTS_B64: ${{ secrets.GH_ACCOUNTS_B64 }}
          GOOGLE_SHEETS_TAB_NAME: ${{ secrets.GOOGLE_SHEETS_TAB_NAME }}
          GOOGLE_SHEETS_TOKEN_B64: ${{ secrets.GOOGLE_SHEETS_TOKEN_B64 }}
          GOOGLE_SHEETS_SHEET_ID: ${{ secrets.GOOGLE_SHEETS_SHEET_ID }}
          GOOGLE_SHEETS_CREDENTIALS_B64: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_B64 }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
          CONTAINER_USER: ${{ secrets.CONTAINER_USER }}
          CONTAINER_PASS: ${{ secrets.CONTAINER_PASS }}
          MATRIX: ${{ secrets.MATRIX }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          python genesi.py --faster ${{ github.event.inputs.faster }}
      - name: Run script without parameters
        if: ${{ !github.event.inputs.accounts_ondemand && !github.event.inputs.faster }}
        env:
          GH_ACCOUNTS_B64: ${{ secrets.GH_ACCOUNTS_B64 }}
          GOOGLE_SHEETS_TAB_NAME: ${{ secrets.GOOGLE_SHEETS_TAB_NAME }}
          GOOGLE_SHEETS_TOKEN_B64: ${{ secrets.GOOGLE_SHEETS_TOKEN_B64 }}
          GOOGLE_SHEETS_SHEET_ID: ${{ secrets.GOOGLE_SHEETS_SHEET_ID }}
          GOOGLE_SHEETS_CREDENTIALS_B64: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_B64 }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
          CONTAINER_USER: ${{ secrets.CONTAINER_USER }}
          CONTAINER_PASS: ${{ secrets.CONTAINER_PASS }}
          MATRIX: ${{ secrets.MATRIX }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          python genesi.py
